title: 52tour
author: 52tour
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  52tour

# social links
twitter_username: 52tour # DO NOT include the @ character, or else the build will fail!
github_username:  52tour # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
